<div class="jumbotron text-center">
  <h1>My First Bootstrap Page</h1>
  <p>Resize this responsive page to see the effect kkk!</p>
</div>

<div class="container">
  <div class="row">
	<div class="col-md-4 col-sm-2">
	  <div class="card">
			<div class="card-header text-center  text-white bg-primary">
	  		<h1>Empresa</h1>
	  	</div>
	  	<div class="card-body text-center">
	  		<h2><a href="#" class="text-dark">Cadastre-se aqui</a></h2>
	  	</div>
	  </div>
	</div>
	<div class="col-md-4 col-sm-8">
		<div class="card">
			<div class="card-header text-center text-white bg-success">
				<h1>Login</h1>
			</div>
			<div class="card-body">
			  	<form action="" method="post">
				  <div class="form-group">
					<label for="email">Email:</label>
					<input type="email" name="email" class="form-control" placeholder="Enter email" id="email" required>
				  </div>
				  <div class="form-group">
					<label for="pwd">Senha:</label>
					<input type="password" name="pwd" class="form-control" placeholder="Enter password" id="pwd" required>
				  </div>
				  <div class="form-group">
					<a href="#">Esqueci minnha senha</a>
				  </div>
				  <button id="btn_aceder" type="submit" class="btn btn-primary">Aceder</button>
				  <?php if($this->view->login == 'erro') {?>
	              <div class="row">
	                <div class="col">
	                  <span class="text text-danger">*E-mail e ou senha inválido(s)</span>
	                </div>
	              </div>
	              <?php } ?>
				</form>
			</div>
		</div>
	</div>
	<div class="col-md-4 col-sm-2 text-center">
	  <div class="card">
	  	<div class="card-header text-center">
	  		<h1>Aluno</h1>
	  	</div>
	  	<div class="card-body text-center">
	  		<h2><a href="/inscreverseAluno" class="text-dark">Cadastre-se aqui</a></h2>
	  	</div>
	  </div>
	</div>
  </div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$('#btn_aceder').on('click', function(){{
		    $.ajax({
		      type: 'GET',
		      url: 'testeAuthAjax',
		      dataType: 'json',
		      data: 'sdfds',
		      success: (dado)=>{
		      	console.log(dado)
		      },
		      error: (e)=>{
		        console.log(e.responseText)
		      }
		    })
		  }})
	})
</script>
