<div class="container">
  <div class="d-flex justify-content-center mt-5">
    <div class="card" style="width: 40rem; margin-top: 3em">
      <div class="card-body">

        

        <div class="row">
          <div class="col">
            <h2 class="text-center mb-4">Crie sua conta</h2>
          </div>
        </div>

        <div class="row">
          <div class="col">
            
            <form action="/registrar" method="post" encType="multipart/form-data">
              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['nome'] ?>" name="nome" class="form-control" placeholder="Nome" required>
              </div>

              <div class="form-group">
                <input type="text" value="<?= $this->view->usuario['cpf'] ?>" name="cpf" class="form-control" placeholder="CPF" onkeypress="$(this).mask('000.000.000-00');" required>
              </div>
              
              <div class="form-group">
                <input type="email" value="<?= $this->view->usuario['email'] ?>"name="email" class="form-control" placeholder="E-mail" required>
              </div>

              <div class="form-group">
                <input type="password" value="<?= $this->view->usuario['senha'] ?>"name="senha" class="form-control" placeholder="Senha" required>
              </div>
              
              <div class="mt-4 mb-4">
                <small class="form-text">
                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
                </small>
              </div>
              <button type="submit" class="btn btn-warning btn-block">Inscrever-se</button>
              <?php if($this->view->erroCadastro) { ?>
                <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente</small>
              <?php } ?>
            </form>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>