<div class="jumbotron container">
	<div class="d-flex justify-content-center mt-5">
		<div class="card" style="width: 90rem;">
			<div class="card-body" style="padding: 3em">
				<!-- Nav tabs -->
				<ul class="nav nav-tabs">
					<li class="nav-item">
						<a class="nav-link active" data-toggle="tab" href="#home">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" data-toggle="tab" href="#menu1">Menu 1</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" data-toggle="tab" href="#menu2">Menu 2</a>
					</li>
				</ul>

				<!-- Tab panes -->
				<form data-toggle="validator" role="form" method="post" action="/teste">
				<div class="tab-content">
					<div class="tab-pane container active" id="home">

						<div class="form-group">
					    <label class="control-label" for="telefone">Telefone:</label>
				      <input type="phone" class="form-control" id="telefone" placeholder="(88) 99999-9999">
					  </div>

						<div class="form-group">
							<label for="cep" class="control-label has-success">CEP</label>
							<input type="text" id="cep" data-minlength="9" onkeypress="$(this).mask('00000-000')" name="cep" class="form-control" placeholder="Ex.: 00000-000" data-error="Por favor, preencha este campo corretamente." required>
							<small class="text-danger"><div class="help-block with-errors"></div></small>
						</div>

						<div class="form-group">
								<label for="uf">Estado</label>
								<select class="form-control" id="uf">
									<option  value="" id="uf" name="uf" ></option>
								</select>
							</div>

							<div class="form-group">
								<label for="cidade">Cidade</label>
								<select name="cidade" class="form-control" id="cidade"></select>
							</div>

							<div class="form-group">
                <label for="endereco">Endereço</label>
                 <input id="endereco" name="endereco" class="form-control" placeholder="Ex.: Rua Mont Alverne" required>
              </div>

              <div class="form-group">
                  <label for="numero">Número</label>
                  <input name="numero" class="form-control col-lg-3" id="numero" placeholder="1234">
              </div>
              <div class="form-group">
                  <label for="bairro">Bairro</label>
                  <input name="bairro" class="form-control col-lg-4" id="bairro" required>
              </div>
					</div>
					<div class="tab-pane container fade" id="menu1">


					</div>
					<div class="tab-pane container fade" id="menu2">
						<button type="submit" class="btn btn-warning btn-block mt-5">Cadastrar Imóvel</button>
					</div>
				</div>
				</form>
			</div>
		</div>

	</div>
</div>
<script type="text/javascript">              
  $.getJSON('http://mendesepereira.neuroteks.com/entrevista/estados_cidades.json', function (data) {
    var items = [];
    var options = '<option value="">escolha um estado</option>';
    $.each(data, function (key, val) {
      options += '<option value="' + val.sigla + '">' + val.nome + '</option>';
    });         
    $("#uf").html(options);       
    $("#uf").change(function () {      
      var options_cidades = '';
      var str = "";         
      $("#uf option:selected").each(function () {
        str += $(this).text();
      });
      $.each(data, function (key, val) {
        if(val.nome == str) {             
          $.each(val.cidades, function (key_city, val_city) {
            options_cidades += '<option value="' + val_city + '">' + val_city + '</option>';                
          });         
        }
      });
      $("#cidade").html(options_cidades);
    }).change();
    //$("#cidade").val($("#cidade"))
  });
</script>
<script type="text/javascript">
  $('#cep').mask('00000-000');
  $('#cpf').mask('000.000.000-00', {reverse: true});
  $('#cnpj').mask('00.000.000/0000-00', {reverse: true});

  $("#cep").focusout(function(){
  //Início do Comando AJAX
  $.ajax({
    //O campo URL diz o caminho de onde virá os dados
    //É importante concatenar o valor digitado no CEP
    url: 'https://viacep.com.br/ws/'+$(this).val()+'/json/unicode/',
    //Aqui você deve preencher o tipo de dados que será lido,
    //no caso, estamos lendo JSON.
    dataType: 'json',
    //SUCESS é referente a função que será executada caso
    //ele consiga ler a fonte de dados com sucesso.
    //O parâmetro dentro da função se refere ao nome da variável
    //que você vai dar para ler esse objeto.
    success: function(resposta){
      //Agora basta definir os valores que você deseja preencher
      //automaticamente nos campos acima.
      $("#endereco").val(resposta.logradouro);
      //$("#complemento").val(resposta.complemento);
      $("#bairro").val(resposta.bairro);
      $("#uf").val(resposta.uf);
      $("#uf").change(function () {      
      var options_cidades = '';
      var str = "";         
      $("#uf option:selected").each(function () {
        str += $(this).text();
      });
      $.each(data, function (key, val) {
        if(val.nome == str) {             
          $.each(val.cidades, function (key_city, val_city) {
            options_cidades += '<option value="' + val_city + '">' + val_city + '</option>';                
          });         
        }
      });
      alert(resposta.localidade)
      $("#cidade").html(options_cidades);
      }).change(function(){
        $('#cidade').val(resposta.localidade)
      })

      alert(resposta.localidade)
      console.log(resposta.localidade)
      //tentar o document.getElementById('cidade').value = resposta.localidade
      //Vamos incluir para que o Número seja focado automaticamente
      //melhorando a experiência do usuário
      $("#numero").focus();
    }
  });
});
</script>
