  <body>
    <section style="padding-top: 66px">
      <div class="container">
        <span class="badge badge-primary"><?= $this->view->id ?></span>
        <span class="badge badge-primary"><?= $this->view->email ?></span>
        <span class="badge badge-primary"><?= $this->view->tipo_usuario ?></span>
      </div>
      <div class="jumbotron container text-center">
        <div class="card-columns">
          <div class="container">
          
          <a href="/curriculo">
            <div id="caixa" class="card">
              <div class="card-body">                
                <div class="card-title text-dark">
                  Cadastrar/Atualizar Currículo
                </div>
              </div>
            </div>
          </a>  

            <div id="caixa" class="card">
              <div class="card-body">
                <div class="card-title text-danger">Vagas Disponíveis
                  <span class="badge badge-primary">13</span>
                </div>
              </div>
            </div>
            
            <a href="#">
            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Imprimir Currículo</div>
              </div>
            </div>
            </a>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Meus Estágios</div>
              </div>
            </div>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Editar Perfil
                  <span class="badge badge-primary">2</span>
                </div>
              </div>
            </div>

            <div class="card">
              <div class="card-body">
                <div class="card-title text-danger">Dúvida/Reclamação/Sugestão</div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </section>
  </body>